# Generated by Django 4.2 on 2023-04-21 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0002_student_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3503bf62-07df-4ef1-a14c-489d8484cbdf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
