# Generated by Django 4.2 on 2023-04-21 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0003_remove_student_id_student_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='uuid',
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.UUID('069f3d10-1353-4985-b659-4f5756b5d317'), editable=False, primary_key=True, serialize=False),
        ),
    ]
